Add prettier linting + verbose hook output
Added verbose error logging to all husky hooks
Added new command in package.json "lint-staged", which calls prettier
--check on all uncommitted changes.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,10 @@
-pnpm format
-pnpm tsc --noEmit
+pnpm lint-staged
+if [ $? -ne 0 ]; then
+  echo "ERROR: Formatter failed -- cancelling push. Run \"pnpm format\""
+  exit 1
+fi
+tsc --noEmit
+if [ $? -ne 0 ]; then
+  echo "ERROR: Typecheck failed -- cancelling push"
+  exit 1
+fi
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,20 @@
-pnpm test
+pnpm lint-staged
+if [ $? -ne 0 ]; then
+  echo "ERROR: Formatter failed -- cancelling push. Run \"pnpm format\""
+  exit 1
+fi
 tsc --noEmit
-pnpm lint
+if [ $? -ne 0 ]; then
+  echo "ERROR: Typecheck failed -- cancelling push"
+  exit 1
+fi
+pnpm test
+if [ $? -ne 0 ]; then
+  echo "ERROR: Tests failed -- cancelling push"
+  exit 1
+fi
 pnpm build
+if [ $? -ne 0 ]; then
+  echo "ERROR: NextJS Build failed -- cancelling push"
+  exit 1
+fi
